### ISSUE TITLE
Présence de doublons 'consolidation-etalab-schema-irve-statique-v-2.2.0-20230808.csv'

### ISSUE THREAD

**Issue by loco-philippe** [BastienGauthier/clean_french_irve#1]
Bonjour Bastien,

J'ai fait une mise à jour de mes indicateurs et je détecte 1957 doublons (par exemple le pdc : FRS33EMB3315811 est présent 4 fois).

J'ai testé également 'clean_french_irve' avant la mise à jour et dans ce cas, il n'y a pas de doublons.

-> 'clean_french_irve' donne bien les mêmes résultats que de mon coté : ok
-> le problème est ailleurs ??

**Comment by BastienGauthier** [comment]
Bonjour Philippe !
Pour bien préciser le problème que tu mentionnes : c'est le fait qu'il y ait des doublons dans le fichier initial de data.gouv.fr malgré les opérations récentes, c'est ça ?
Si c'est le cas, je ne pense pas être la bonne personne car je ne fait pas partie de data.gouv.fr, je propose simplement un traitement automatique supplémentaire ici.

**Comment by loco-philippe** [comment]
Bonjour Bastien,

En fait, c'est dans le fichier mis à disposition (donc après le traitement d'élimination des doublons) qu'il reste quand même des doublons ( ce que je comprends pas puisque ton traitement fonctionne bien ??). Tu peux vérifier avec la référence de PDC que j'ai indiquée.

**Comment by BastienGauthier** [comment]
Oui, dans ce cas je dois fouiller dans le script de consolidation de data.gouv.fr, mais je suppose a priori que c'est une histoire de doublon inter-fichiers ou intra-fichiers et que seule l'une des catégories est enlevée. Je dois confirmer ça encore.

**Comment by loco-philippe** [comment]
Bonjour Bastien,

Effectivement, ça serait intéressant d'avoir une vision complète de l’enchaînement des différents scripts pour comprendre d'ou vient le problème (pas simple...).

Si besoin, je peux essayer de caractériser les données qui ont disparu (en faisant un diff entre le fichier à mi-juin et celui actuel), est-ce que ça pourrait aider ?

**Comment by BastienGauthier** [comment]
Cela pourra peut-être aider data.gouv.fr à identifier les fichiers en erreur, mais je pense qu'ils ont un suivi de leur côté déjà. Cependant, pour pallier aux disparitions subites, je viens de créer un fichier "[robust](https://github.com/BastienGauthier/clean_french_irve/blob/main/data/df_irve_etalab_cleaned_robust.csv)" qui ne va s'actualiser que s'il n'y a pas eu de drop de donnée. Est-ce que ça peut aider pour ton besoin ?

**Comment by loco-philippe** [comment]
Bonjour Bastien,

Je te fais suivre (cf PJ) les indicateurs que je diffuse au travers de la
réutilisation
<https://nbviewer.org/github/loco-philippe/Environmental-Sensing/blob/main/python/Validation/irve/Analyse/IRVE_indicateurs.ipynb>
.

-> pour les doublons, ça montre bien que ton action a été efficace (même
s'il en reste toujours un peu)
-> pour le fichier "robust", c'est intéressant effectivement de pouvoir
voir les journées pour lesquelles il y a eu des "disparitions subites" (il
vaut mieux éviter de construire des indicateurs sur ces journées). Mais
dans ce cas, pourquoi est-ce qu'on publie quand même les données avec des
écarts importants (par exemple du 8 au 11 septembre où il manquait 5 000
pdc ??)

Bonne journée

**Comment by BastienGauthier** [comment]
Je suis revenu là dessus, et ça m'a permis de confirmer et de préciser ce que l'on s'est dit. Je vais donc clore cette issue maintenant que le problème est éclairci.

-> il existe bien des cas où un même pdc est déclaré dans plusieurs endroits, d'où les doublons restants malgré le filtre de l'etalab. Ce n'est que le second filtre que je fais ici qui les enlève (arbitrairement, car on je ne sais pas choisir entre les deux sources d'information)

-> Certains déclarent des id_pdc_itinérance (la clef unique) en "Non concerné" (environ 100 repo, soit de l'ordre de 500pdc je dirais). Le dédoublonnage les efface donc, puisque leur id est le même.

Finalement, pour pallier à ça en gérant la volatilité, j'ai créé un fichier "combiné", qui ajoute les nouvelles informations aux informations qui sont déjà présentes. En effet, je pars du constat que s'il y a 1000 pdc qui disparaissent, et 1000 pdc qui réapparaisse 2 jours plus tard, rien ne dit que ce sont les 1000 même. (https://github.com/BastienGauthier/clean_french_irve/pull/2)
